version: "3.8"
services:
 
  # POSTGRESQL
  psql:
    image: postgres:10
    environment:
      - POSTGRES_DB=musicevent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: psql
    volumes:
      - ./psql/musicevent.sql:/docker-entrypoint-initdb.d/musicevent.sql
      - psqldata:/var/lib/postgresql/data
      
    expose:
      - 5432
   
  # MONGODB
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes: 
      - mongodbdata:/data/db
      
  # WEB
  web:
      build: .
      ports:
        - "5000:5000"
      volumes:
        - ./app/:/home/app/
      depends_on:
        - psql
        - mongodb
        
volumes:
  mongodbdata:
    driver: local
  psqldata:
    driver: local
