version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - psql
      - mongodb
  psql:
    image: postgres:10
    environment:
      - POSTGRES_DB=musicevent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./psql/musicevent.sql:/docker-entrypoint-initdb.d/musicevent.sql
    expose:
      - 5432
      
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
